name: dtupy-analysis
channels:
  - defaults
  - conda-forge
dependencies:
  - alive-progress=3.1.5
  - matplotlib-base=3.9.2
  - numpy=1.26.4
  - numpy-base=1.26.4
  - pandas=2.2.2
  - python=3.12.3
  - scipy=1.13.1
  - termcolor=2.1.0
  - tqdm=4.66.5
